import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useMemo, useState } from "react";
import BlogPreview from "@/components/BlogPreview";
import { getBlogs } from "../../server/blogs";
import { IBlogPost } from "@/types/blogType";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = ({
  blogData,
  tags,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [filterWord, setFilterWord] = useState<string[]>([]);

  const filteredBlog: IBlogPost[] = useMemo(() => {
    if (filterWord.length > 0) {
      return blogData.filter((blog: IBlogPost) => {
        return filterWord.every((filter) => blog.tags.includes(filter));
      });
    } else {
      return blogData;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filterWord]);

  const filterLabel = (tag: any) => {
    let tagText: string = tag.innerText;
    if (filterWord.includes(tagText)) {
      const removeSelected = filterWord.filter((word) => word !== tagText);
      setFilterWord(removeSelected);
    } else {
      setFilterWord([...filterWord, tagText]);
    }
  };

  return (
    <>
      <Head>
        <title>Blog Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen overflow-auto flex flex-col items-center bg-zinc-600 text-neutral-300">
        <div className="mt-3 text-center">
          <h1 className="text-[4rem]">Welcome to Blog</h1>
          <p className="">NextJS, Typescript, TailwindCSS </p>
        </div>

        <section className="flex flex-col items-center text-[1.15rem] mt-12">
          <div className="flex gap-3 mb-12">
            {tags.map((tag: string, idx: number) => {
              return (
                <button
                  className={`${
                    filterWord.includes(tag)
                      ? "label-selected hover:bg-sky-400 transition-all duration-300"
                      : "label hover:bg-sky-400 transition-all duration-300"
                  }`}
                  key={idx}
                  onClick={(e) => filterLabel(e.target)}
                >
                  {tag}
                </button>
              );
            })}
          </div>
          <div className="list-blog grid grid-cols-3">
            {filteredBlog.map((blog: IBlogPost) => {
              return (
                <div
                  key={blog.id}
                  className="col-span-1 overflow-hidden mx-6 mb-6 bg-neutral-300 text-zinc-800 
                  rounded-lg cursor-pointer p-4 hover:bg-neutral-400 hover:text-neutral-300 transition-all duration-200"
                >
                  <a href={blog.url} target="_blank" rel="noreferrer">
                    <BlogPreview
                      title={blog.title}
                      bodyText={blog.bodyText}
                      createdAt={blog.createdAt}
                      author={blog.author}
                      tags={blog.tags}
                    />
                  </a>
                </div>
              );
            })}
          </div>
        </section>
      </main>
    </>
  );
};
export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  let blogs: IBlogPost[] = await getBlogs();
  let tags: string[] = [];
  for (const blog of blogs) {
    for (const tag of blog.tags) {
      if (!tags.includes(tag)) {
        tags.push(tag);
      }
    }
  }

  return {
    props: {
      blogData: blogs,
      tags: tags,
    },
  };
};
